/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AlunoRouteImport } from './routes/aluno'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlunoIndexRouteImport } from './routes/aluno/index'
import { Route as AlunoVideosRouteImport } from './routes/aluno/videos'
import { Route as AlunoSuporteRouteImport } from './routes/aluno/suporte'
import { Route as AlunoPerfilRouteImport } from './routes/aluno/perfil'
import { Route as AlunoModulosRouteImport } from './routes/aluno/modulos'
import { Route as AlunoForumRouteImport } from './routes/aluno/forum'
import { Route as AlunoFormacaoRouteImport } from './routes/aluno/formacao'
import { Route as AlunoCertificadoRouteImport } from './routes/aluno/certificado'
import { Route as AlunoAvaliacoesRouteImport } from './routes/aluno/avaliacoes'
import { Route as AlunoAtividadesRouteImport } from './routes/aluno/atividades'
import { Route as AlunoApostilasRouteImport } from './routes/aluno/apostilas'
import { Route as AlunoAdminRouteImport } from './routes/aluno/admin'
import { Route as AlunoAdminIndexRouteImport } from './routes/aluno/admin.index'
import { Route as AlunoModulosIdRouteImport } from './routes/aluno/modulos.$id'
import { Route as AlunoAulasIdRouteImport } from './routes/aluno/aulas.$id'
import { Route as AlunoAdminModulosRouteImport } from './routes/aluno/admin.modulos'
import { Route as AlunoAdminAlunosRouteImport } from './routes/aluno/admin.alunos'

const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoRoute = AlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoIndexRoute = AlunoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoVideosRoute = AlunoVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoSuporteRoute = AlunoSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoPerfilRoute = AlunoPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoModulosRoute = AlunoModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoForumRoute = AlunoForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoFormacaoRoute = AlunoFormacaoRouteImport.update({
  id: '/formacao',
  path: '/formacao',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoCertificadoRoute = AlunoCertificadoRouteImport.update({
  id: '/certificado',
  path: '/certificado',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoAvaliacoesRoute = AlunoAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoAtividadesRoute = AlunoAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoApostilasRoute = AlunoApostilasRouteImport.update({
  id: '/apostilas',
  path: '/apostilas',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoAdminRoute = AlunoAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoAdminIndexRoute = AlunoAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlunoAdminRoute,
} as any)
const AlunoModulosIdRoute = AlunoModulosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AlunoModulosRoute,
} as any)
const AlunoAulasIdRoute = AlunoAulasIdRouteImport.update({
  id: '/aulas/$id',
  path: '/aulas/$id',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoAdminModulosRoute = AlunoAdminModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => AlunoAdminRoute,
} as any)
const AlunoAdminAlunosRoute = AlunoAdminAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AlunoAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/aluno/admin': typeof AlunoAdminRouteWithChildren
  '/aluno/apostilas': typeof AlunoApostilasRoute
  '/aluno/atividades': typeof AlunoAtividadesRoute
  '/aluno/avaliacoes': typeof AlunoAvaliacoesRoute
  '/aluno/certificado': typeof AlunoCertificadoRoute
  '/aluno/formacao': typeof AlunoFormacaoRoute
  '/aluno/forum': typeof AlunoForumRoute
  '/aluno/modulos': typeof AlunoModulosRouteWithChildren
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/aluno/suporte': typeof AlunoSuporteRoute
  '/aluno/videos': typeof AlunoVideosRoute
  '/aluno/': typeof AlunoIndexRoute
  '/aluno/admin/alunos': typeof AlunoAdminAlunosRoute
  '/aluno/admin/modulos': typeof AlunoAdminModulosRoute
  '/aluno/aulas/$id': typeof AlunoAulasIdRoute
  '/aluno/modulos/$id': typeof AlunoModulosIdRoute
  '/aluno/admin/': typeof AlunoAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/aluno/apostilas': typeof AlunoApostilasRoute
  '/aluno/atividades': typeof AlunoAtividadesRoute
  '/aluno/avaliacoes': typeof AlunoAvaliacoesRoute
  '/aluno/certificado': typeof AlunoCertificadoRoute
  '/aluno/formacao': typeof AlunoFormacaoRoute
  '/aluno/forum': typeof AlunoForumRoute
  '/aluno/modulos': typeof AlunoModulosRouteWithChildren
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/aluno/suporte': typeof AlunoSuporteRoute
  '/aluno/videos': typeof AlunoVideosRoute
  '/aluno': typeof AlunoIndexRoute
  '/aluno/admin/alunos': typeof AlunoAdminAlunosRoute
  '/aluno/admin/modulos': typeof AlunoAdminModulosRoute
  '/aluno/aulas/$id': typeof AlunoAulasIdRoute
  '/aluno/modulos/$id': typeof AlunoModulosIdRoute
  '/aluno/admin': typeof AlunoAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/aluno/admin': typeof AlunoAdminRouteWithChildren
  '/aluno/apostilas': typeof AlunoApostilasRoute
  '/aluno/atividades': typeof AlunoAtividadesRoute
  '/aluno/avaliacoes': typeof AlunoAvaliacoesRoute
  '/aluno/certificado': typeof AlunoCertificadoRoute
  '/aluno/formacao': typeof AlunoFormacaoRoute
  '/aluno/forum': typeof AlunoForumRoute
  '/aluno/modulos': typeof AlunoModulosRouteWithChildren
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/aluno/suporte': typeof AlunoSuporteRoute
  '/aluno/videos': typeof AlunoVideosRoute
  '/aluno/': typeof AlunoIndexRoute
  '/aluno/admin/alunos': typeof AlunoAdminAlunosRoute
  '/aluno/admin/modulos': typeof AlunoAdminModulosRoute
  '/aluno/aulas/$id': typeof AlunoAulasIdRoute
  '/aluno/modulos/$id': typeof AlunoModulosIdRoute
  '/aluno/admin/': typeof AlunoAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aluno'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/aluno/admin'
    | '/aluno/apostilas'
    | '/aluno/atividades'
    | '/aluno/avaliacoes'
    | '/aluno/certificado'
    | '/aluno/formacao'
    | '/aluno/forum'
    | '/aluno/modulos'
    | '/aluno/perfil'
    | '/aluno/suporte'
    | '/aluno/videos'
    | '/aluno/'
    | '/aluno/admin/alunos'
    | '/aluno/admin/modulos'
    | '/aluno/aulas/$id'
    | '/aluno/modulos/$id'
    | '/aluno/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/aluno/apostilas'
    | '/aluno/atividades'
    | '/aluno/avaliacoes'
    | '/aluno/certificado'
    | '/aluno/formacao'
    | '/aluno/forum'
    | '/aluno/modulos'
    | '/aluno/perfil'
    | '/aluno/suporte'
    | '/aluno/videos'
    | '/aluno'
    | '/aluno/admin/alunos'
    | '/aluno/admin/modulos'
    | '/aluno/aulas/$id'
    | '/aluno/modulos/$id'
    | '/aluno/admin'
  id:
    | '__root__'
    | '/'
    | '/aluno'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/aluno/admin'
    | '/aluno/apostilas'
    | '/aluno/atividades'
    | '/aluno/avaliacoes'
    | '/aluno/certificado'
    | '/aluno/formacao'
    | '/aluno/forum'
    | '/aluno/modulos'
    | '/aluno/perfil'
    | '/aluno/suporte'
    | '/aluno/videos'
    | '/aluno/'
    | '/aluno/admin/alunos'
    | '/aluno/admin/modulos'
    | '/aluno/aulas/$id'
    | '/aluno/modulos/$id'
    | '/aluno/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlunoRoute: typeof AlunoRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno': {
      id: '/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/': {
      id: '/aluno/'
      path: '/'
      fullPath: '/aluno/'
      preLoaderRoute: typeof AlunoIndexRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/videos': {
      id: '/aluno/videos'
      path: '/videos'
      fullPath: '/aluno/videos'
      preLoaderRoute: typeof AlunoVideosRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/suporte': {
      id: '/aluno/suporte'
      path: '/suporte'
      fullPath: '/aluno/suporte'
      preLoaderRoute: typeof AlunoSuporteRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/perfil': {
      id: '/aluno/perfil'
      path: '/perfil'
      fullPath: '/aluno/perfil'
      preLoaderRoute: typeof AlunoPerfilRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/modulos': {
      id: '/aluno/modulos'
      path: '/modulos'
      fullPath: '/aluno/modulos'
      preLoaderRoute: typeof AlunoModulosRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/forum': {
      id: '/aluno/forum'
      path: '/forum'
      fullPath: '/aluno/forum'
      preLoaderRoute: typeof AlunoForumRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/formacao': {
      id: '/aluno/formacao'
      path: '/formacao'
      fullPath: '/aluno/formacao'
      preLoaderRoute: typeof AlunoFormacaoRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/certificado': {
      id: '/aluno/certificado'
      path: '/certificado'
      fullPath: '/aluno/certificado'
      preLoaderRoute: typeof AlunoCertificadoRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/avaliacoes': {
      id: '/aluno/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/aluno/avaliacoes'
      preLoaderRoute: typeof AlunoAvaliacoesRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/atividades': {
      id: '/aluno/atividades'
      path: '/atividades'
      fullPath: '/aluno/atividades'
      preLoaderRoute: typeof AlunoAtividadesRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/apostilas': {
      id: '/aluno/apostilas'
      path: '/apostilas'
      fullPath: '/aluno/apostilas'
      preLoaderRoute: typeof AlunoApostilasRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/admin': {
      id: '/aluno/admin'
      path: '/admin'
      fullPath: '/aluno/admin'
      preLoaderRoute: typeof AlunoAdminRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/admin/': {
      id: '/aluno/admin/'
      path: '/'
      fullPath: '/aluno/admin/'
      preLoaderRoute: typeof AlunoAdminIndexRouteImport
      parentRoute: typeof AlunoAdminRoute
    }
    '/aluno/modulos/$id': {
      id: '/aluno/modulos/$id'
      path: '/$id'
      fullPath: '/aluno/modulos/$id'
      preLoaderRoute: typeof AlunoModulosIdRouteImport
      parentRoute: typeof AlunoModulosRoute
    }
    '/aluno/aulas/$id': {
      id: '/aluno/aulas/$id'
      path: '/aulas/$id'
      fullPath: '/aluno/aulas/$id'
      preLoaderRoute: typeof AlunoAulasIdRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/admin/modulos': {
      id: '/aluno/admin/modulos'
      path: '/modulos'
      fullPath: '/aluno/admin/modulos'
      preLoaderRoute: typeof AlunoAdminModulosRouteImport
      parentRoute: typeof AlunoAdminRoute
    }
    '/aluno/admin/alunos': {
      id: '/aluno/admin/alunos'
      path: '/alunos'
      fullPath: '/aluno/admin/alunos'
      preLoaderRoute: typeof AlunoAdminAlunosRouteImport
      parentRoute: typeof AlunoAdminRoute
    }
  }
}

interface AlunoAdminRouteChildren {
  AlunoAdminAlunosRoute: typeof AlunoAdminAlunosRoute
  AlunoAdminModulosRoute: typeof AlunoAdminModulosRoute
  AlunoAdminIndexRoute: typeof AlunoAdminIndexRoute
}

const AlunoAdminRouteChildren: AlunoAdminRouteChildren = {
  AlunoAdminAlunosRoute: AlunoAdminAlunosRoute,
  AlunoAdminModulosRoute: AlunoAdminModulosRoute,
  AlunoAdminIndexRoute: AlunoAdminIndexRoute,
}

const AlunoAdminRouteWithChildren = AlunoAdminRoute._addFileChildren(
  AlunoAdminRouteChildren,
)

interface AlunoModulosRouteChildren {
  AlunoModulosIdRoute: typeof AlunoModulosIdRoute
}

const AlunoModulosRouteChildren: AlunoModulosRouteChildren = {
  AlunoModulosIdRoute: AlunoModulosIdRoute,
}

const AlunoModulosRouteWithChildren = AlunoModulosRoute._addFileChildren(
  AlunoModulosRouteChildren,
)

interface AlunoRouteChildren {
  AlunoAdminRoute: typeof AlunoAdminRouteWithChildren
  AlunoApostilasRoute: typeof AlunoApostilasRoute
  AlunoAtividadesRoute: typeof AlunoAtividadesRoute
  AlunoAvaliacoesRoute: typeof AlunoAvaliacoesRoute
  AlunoCertificadoRoute: typeof AlunoCertificadoRoute
  AlunoFormacaoRoute: typeof AlunoFormacaoRoute
  AlunoForumRoute: typeof AlunoForumRoute
  AlunoModulosRoute: typeof AlunoModulosRouteWithChildren
  AlunoPerfilRoute: typeof AlunoPerfilRoute
  AlunoSuporteRoute: typeof AlunoSuporteRoute
  AlunoVideosRoute: typeof AlunoVideosRoute
  AlunoIndexRoute: typeof AlunoIndexRoute
  AlunoAulasIdRoute: typeof AlunoAulasIdRoute
}

const AlunoRouteChildren: AlunoRouteChildren = {
  AlunoAdminRoute: AlunoAdminRouteWithChildren,
  AlunoApostilasRoute: AlunoApostilasRoute,
  AlunoAtividadesRoute: AlunoAtividadesRoute,
  AlunoAvaliacoesRoute: AlunoAvaliacoesRoute,
  AlunoCertificadoRoute: AlunoCertificadoRoute,
  AlunoFormacaoRoute: AlunoFormacaoRoute,
  AlunoForumRoute: AlunoForumRoute,
  AlunoModulosRoute: AlunoModulosRouteWithChildren,
  AlunoPerfilRoute: AlunoPerfilRoute,
  AlunoSuporteRoute: AlunoSuporteRoute,
  AlunoVideosRoute: AlunoVideosRoute,
  AlunoIndexRoute: AlunoIndexRoute,
  AlunoAulasIdRoute: AlunoAulasIdRoute,
}

const AlunoRouteWithChildren = AlunoRoute._addFileChildren(AlunoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlunoRoute: AlunoRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
